Simple head
ksdenisova/HTTP-Server pull request #11
Opened 2021-12-21 15:22 UTC by ksdenisova

**Feature**: Simple HEAD

  **Scenario**: Executing a HEAD request to /simple_get
    **Given** I make a HEAD request to "/simple_get"
    **Then** my response should have status code 200
    **And** my response should have an empty body

  **Scenario**: HEAD does not include body
    **Given** I make a HEAD request to "/head_request"
    **Then** my response should have status code 200
    **And** my response should have an empty body

* All existing test endpoints should be updated with the required headers

[Trello](https://trello.com/c/oG0m1tc5/12-simple-head)

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/89826596/146954133-ff8b4e57-0d6c-46e8-9fd1-0cec49e5cabd.png">

**Refactoring:**

- Updated `Headers` to support `Content-Length` and `Content-Type` headers.
- Added `Content-Length` and `Content-Type` headers to `SimplePost` and `SimpleGetWithBody` handlers.
- Changed parsing the body in `Request.Parser`.

2021-12-21 15:45 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_get_with_body.ex
> +    headers = %Headers{content_length: byte_size(body), content_type: "text/plain"}
It should not be the responsibility of a user of the http_server to calculate their own body size.  What can you do in the http server (and not in the tests handlers) to do this?

2021-12-21 15:46 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
Where is this being used? I did not think the http server spec requires an endpoint for /simple_head for the acceptance tests?

2021-12-21 15:52 UTC, Aoxian commented on lib/routes.ex
> +        Handler.SimpleHead
a routes file, which is essentially a configuration file for your implementation, should not have HEAD as a method. The http server library / framework you are writing should handle the HEAD request for any GET that is implemented.

2021-12-21 15:55 UTC, Aoxian requested changes
The approach taken in it current state follows the pattern of placing the burden of implementing a HEAD method on the user of the library / framework. Instead, when a user implements a GET route, HEAD should be provided for them by the http server library.  Very similar to how you have handled when a route is not found.  Please refactor.

2021-12-21 18:15 UTC, ksdenisova commented on lib/http_server_fixture/handler/simple_get_with_body.ex
> +    headers = %Headers{content_length: byte_size(body), content_type: "text/plain"}
I'll move it to the `Response` module. I just need to think how to add this only if response has a body.

2021-12-21 18:23 UTC, ksdenisova commented on lib/http_server_fixture/handler/simple_head.ex
> +end
This is used in this acceptance test:

  **Scenario**: HEAD does not include body
    **Given** I make a HEAD request to "/head_request"
    **Then** my response should have status code 200
    **And** my response should have an empty body

This is actually interesting, we didn't have a `GET` method allowed for this endpoint. How should I support this? Should I return a `SimpleGet` handler for this endpoint?

2021-12-21 18:26 UTC, ksdenisova commented on lib/routes.ex
> +        Handler.SimpleHead
I understand it now. I'll think about how I can approach this differently.

2021-12-21 19:04 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
There is nothing about this acceptance test that says HEAD is the only option.  You should be able to add a GET route to `/head_request` and that means the HEAD request to the enpoint would return correclty.

2021-12-21 19:07 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
What I suggest is adding the following `Handler` to the fixture:

```elixir
defmodule HttpServerFixture.Handler.SimpleHead do
  @behaviour HttpServer.Handler

  @impl HttpServer.Handler
  def handle(_request, builder) do
    body = "This would return in a GET, but not in a HEAD"
    headers = %Headers{content_type: "text/plain"}

    builder.new_response()
    |>builder.add_headers(headers)
    |> builder.add_body(body)
  end
end
```

2021-12-21 19:09 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
I would expect a HEAD request to return the following:
```
HTTP/1.1 HEAD 200, OK
Content-Type: text/plain
Content-Length: 45
```

2021-12-21 19:11 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
I think that would help you flush out the functionality, but also pass the acceptance test.

2021-12-21 21:55 UTC, ksdenisova commented on lib/http_server_fixture/handler/simple_head.ex
> +end
> I would expect a HEAD request to return the following:
> 
> ```
> HTTP/1.1 HEAD 200, OK
> Content-Type: text/plain
> Content-Length: 0
> ```

I'm trying to understand if response to HEAD request should contain the representation headers. From [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages) I see that they applied if the message has a body:

`Representation headers like Content-Type that describe the original format of the message data and any encoding applied (only present if the message has a body).` 

And also that [Representation headers](https://developer.mozilla.org/en-US/docs/Glossary/Representation_header) describe the body content that would be selected if the resource was actually requested:

`Representation headers may be present in both HTTP request and response messages. If sent as a response to a HEAD request, they describe the body content that would be selected if the resource was actually requested.`

Does this mean that if the request has a body, we should include those headers in the response, and not otherwise?

2021-12-21 23:06 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
you are correct, in this case it would not have the headers.  Its a very frustrating thing that the acceptance tests are minimal.

2021-12-21 23:20 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
Here is another hypothetical, perhaps this will help understand what I am trying to communicate here. ....

```elixir
defmodule HttpServerFixture.Handler.HeadExample do
  @behaviour HttpServer.Handler

  @impl HttpServer.Handler
  def handle(_request, builder) do
    body = "This body shows up in a GET but not in a HEAD"
    headers = %Headers{content_type: "text/plain"}

    builder.new_response()
    |>builder.add_headers(headers)
    |> builder.add_body(body)
  end
end
```
Route:
```elixir
def handle(%Request{resource: "/head_example", method: method}) do
    case method do
      "GET" ->
        Handler.HeadRequest
      _ ->
        raise Exception.MethodNotFoundError
    end
  end
```

GET response:
```
200 OK
Content-Type: text/plain 
Content-Length: 45

This body shows up in a GET but not in a HEAD
```

HEAD response:
```
200 OK
```

2021-12-21 23:45 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_head.ex
> +end
I really hope this is helpful feedback.  If not, we can sync up tomorrow during the weekly pairing session and work through it.

2021-12-22 14:39 UTC, ksdenisova commented on lib/http_server_fixture/handler/simple_head.ex
> +end
I understand what you mean. If I won't implement it until pairing session, then I will be glad to do it together. Thank you for the explanation and such good examples!

2021-12-22 18:10 UTC, ksdenisova commented
I moved `Content-Length` calculation to `Response`, refactored `Router` to support `HEAD` request. I want to refactor `find_handler` to more functional way.

I checked that `body` is empty when making `HEAD` request to `head_request` endpoint using Postman: 

<img width="333" alt="image" src="https://user-images.githubusercontent.com/89826596/147136009-f9a8f8f9-3bd7-4ee0-9b97-df2ece75343b.png">

But when I  make `GET` request to the same endpoint, response has a `body`:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/89826596/147136573-19d9e5dc-742d-4d06-a24a-8948a56b3a8e.png">

I still need to figure out how not to send Content length/type if body is empty. I'll continue to work on this tomorrow.

2021-12-22 20:08 UTC, Aoxian commented on lib/http_server/response/response.ex
> +  def update_headers(response), do: response
(this is a non-blocking comment)

When is it better to use guards and when is it better to pattern match?

For example, here is an alternate solution using pattern matching:
```suggestion
  def update_headers(%Response{body: nil} = response), do: response

  def update_headers(%Response{headers: headers, body: body} = response) do
    %Response{response | headers: %{headers | content_length: byte_size(body)}}
  end

  
```

2021-12-22 20:13 UTC, Aoxian commented on lib/http_server/response/response.ex
> +  def update_headers(response) when response.body != nil do
If we are expecting a %Response{} struct to be passed in, you can make sure that the function pattern matches on it, to prevent incorrect data being passed in. (you probably want to do this anytime in the code you are passing around a custom Struct.

```suggestion
  def update_headers(%Response{} = response) when response.body != nil do
```

Then, anytime `#update_headers/1` is called with something other than a response you could ignore it, or maybe even raise an error.

```exlixir
  def update_headers(_), do: nil
```

2021-12-22 20:39 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_post.ex
> +    |>builder.add_headers(headers)
```suggestion
    |> builder.add_headers(headers)
```
![image](https://user-images.githubusercontent.com/26009042/147152513-6f02eee3-975b-4c73-879e-120e744da251.png)

2021-12-22 20:52 UTC, Aoxian commented on lib/http_server/router.ex
> +    end
Any time you have a case, its an opportunity to use pattern matching.  

```elixir
def find_handler(routes \\ Routes, %Request{method: "HEAD"} = request) do
  ...
end

def find_handler(routes \\ Routes, %Request{} = request), do: routes.handle(request)

def find_handler(_, _), do: nil
```

2021-12-22 20:54 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_post.ex
> +    |>builder.add_headers(headers)
I am actually surprised the linter did not find this.

2021-12-23 14:41 UTC, ksdenisova commented on lib/http_server/router.ex
> +    end
I actually tried to implement something similar yesterday, but I had an error about using default argument (`Routes`) twice. I'm going to find a way to use a pattern matching here.

2021-12-23 14:42 UTC, ksdenisova commented on lib/http_server_fixture/handler/simple_post.ex
> +    |>builder.add_headers(headers)
It's possible that this rule is disabled. I'll take a look.

2021-12-23 14:46 UTC, ksdenisova commented on lib/http_server/response/response.ex
> +  def update_headers(response) when response.body != nil do
This is a good suggestion. I'll change it and will keep it in mind for the future.

2021-12-23 15:18 UTC, ksdenisova commented on lib/http_server/response/response.ex
> +  def update_headers(response), do: response
We use pattern match to check if some data (variables, maps, structs etc.) matches a specific pattern.

Guards are more powerful that pattern match. They uses pattern matching to achieve more complex checks: 
> [Guards](https://hexdocs.pm/elixir/master/patterns-and-guards.html) are a way to augment pattern matching with more complex checks. They are allowed in a predefined set of constructs where pattern matching is allowed, such as function definitions, case clauses, and others.

I think in our case it is enough to use only patterns. I'll make changes.

2021-12-23 15:37 UTC, Aoxian commented on lib/http_server/router.ex
> +    end
this is not blocking, so if you cannot figure something out just let us know!

2021-12-23 18:31 UTC, Aoxian commented on lib/http_server/router.ex
> +    |> routes.handle()
This is looking good.  Since we know this is for `HEAD`, why not just strip the headers right here and simplify things.
```suggestion
  def find_handler(routes \\ Routes, request)

  def find_handler(routes, %Request{method: "HEAD"} = request) do
    response = %Request{request | method: "GET"} |> routes.handle()
    
    %Response{ response | body: nil }
```

2021-12-23 18:32 UTC, ksdenisova commented on lib/http_server/router.ex
> +    end
I figured it out. I added a header with default values as Mix suggested.

<img width="1019" alt="CleanShot 2021-12-23 at 10 45 26@2x" src="https://user-images.githubusercontent.com/89826596/147279505-e97a0949-cfa6-4701-91fa-6a76fddac013.png">

2021-12-23 18:35 UTC, Aoxian commented on lib/http_server/router.ex
> +    |> routes.handle()
I see you have this in the `Response`.  I think that actually makes more sense, it should not be the routers job to strip the body.

2021-12-23 18:37 UTC, ksdenisova commented on lib/http_server_fixture/handler/simple_post.ex
> +    |>builder.add_headers(headers)
No, the rule `Credo.Check.Consistency.SpaceAroundOperators, []` is active, but it looks like it checks space around operators like +, -, * and /. It's possible doesn't check if after the pipe operator.

2021-12-23 18:38 UTC, Aoxian approved these changes
Nice effort!

2021-12-23 18:40 UTC, Aoxian commented on lib/http_server_fixture/handler/simple_post.ex
> +    |>builder.add_headers(headers)
Sounds like an opportunity for an open source PR for Credo (assuming its an open source project).

2021-12-23 18:42 UTC, ksdenisova commented
> Nice effort!

Thank you for helping me with this!!

2021-12-23 18:54 UTC, merged